// <auto-generated>
//     This code was generated by the GSharp resx code generator, from the
//     matching .resx file. Changes to this file may cause incorrect behavior
//     and will be lost if the code is regenerated.
// </auto-generated>

package Oahu.Core.Properties

/// A strongly-typed resource class, for looking up localized strings, etc.
internal class Resources {
    internal init() { }

    shared {
        var resourceMan System.Resources.ResourceManager?
        var resourceCulture System.Globalization.CultureInfo?

        /// Returns the cached ResourceManager instance used by this class.
        prop ResourceManager System.Resources.ResourceManager {
            get {
                if resourceMan == nil {
                    var temp = System.Resources.ResourceManager(
                        "Oahu.Core.Properties.Resources",
                        typeof(Resources).Assembly
                    )
                    resourceMan = temp
                }

                return resourceMan!!
            }
        }

        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        prop Culture System.Globalization.CultureInfo? {
            get {
                return resourceCulture
            }
            set {
                resourceCulture = value
            }
        }

        /// Looks up a localized string similar to .m4b.
        prop DecryptedFileExt string -> ResourceManager.GetString("DecryptedFileExt", resourceCulture)!!

        /// Looks up a localized string similar to .aaxc.
        prop EncryptedFileExt string -> ResourceManager.GetString("EncryptedFileExt", resourceCulture)!!

        /// Looks up a localized string similar to .aax.
        prop ExportedFileExt string -> ResourceManager.GetString("ExportedFileExt", resourceCulture)!!
    }
}
